services:
  postgres:
    container_name: ecommerce-api-dev

    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: development
      DB_HOST: host.docker.internal      # ← reaches host machine from inside container
      DB_PORT: 5433                       # ← the host port your Postgres is on
      DB_NAME: ecommerce_db
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      JWT_SECRET: dev-secret-change-in-production

    ports:
      - "8080:8080"

    extra_hosts:
      - "host.docker.internal:host-gateway"   # ← required on Linux; harmless on Mac/Windows

    volumes:
      - ./logs:/app/logs            # optional: mount logs folder for easy viewing